/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 042749f91e3968ed185c7f372f5610e6)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/_worker.js/index");
		durableNamespaces: "OrchestratorAgent" | "NotebookLMAgent" | "NotebookLMMcpAgent" | "TranscriptionAgent" | "Sandbox" | "JobScannerAgent" | "JobAnalysisAgent" | "SyncBroadcastAgent" | "RoleChatAgent";
	}
	interface Env {
		KV: KVNamespace;
		SESSIONS: KVNamespace;
		R2_AUDIO_BUCKET: R2Bucket;
		R2_FILES_BUCKET: R2Bucket;
		R2_JOBS_BUCKET: R2Bucket;
		DB: D1Database;
		VECTORIZE_CAREER_MEMORY: VectorizeIndex;
		VECTORIZE_JOBS: VectorizeIndex;
		EMAIL_OUT: SendEmail;
		GITHUB_TOKEN: SecretsStoreSecret;
		CLOUDFLARE_ACCOUNT_ID: SecretsStoreSecret;
		CLOUDFLARE_WRANGLER_API_TOKEN: SecretsStoreSecret;
		WORKER_API_KEY: SecretsStoreSecret;
		CLOUDFLARE_IMAGES_STREAM_TOKEN: SecretsStoreSecret;
		AGENTIC_WORKER_API_KEY: SecretsStoreSecret;
		CLOUDFLARE_AI_GATEWAY_TOKEN: SecretsStoreSecret;
		CF_BROWSER_RENDER_TOKEN: SecretsStoreSecret;
		JULES_API_KEY: SecretsStoreSecret;
		GOOGLE_CREDS_SA_PRIVATE_KEY_PT_1: SecretsStoreSecret;
		GOOGLE_CREDS_SA_PRIVATE_KEY_PT_2: SecretsStoreSecret;
		GOOGLE_CREDS_SA_CLIENT_EMAIL: SecretsStoreSecret;
		NOTEBOOKLM_AUTH_TOKEN: SecretsStoreSecret;
		GOOGLE_MAPS_API: SecretsStoreSecret;
		GEMINI_API_KEY: SecretsStoreSecret;
		BROWSER: Fetcher;
		AI: Ai;
		ASSETS: Fetcher;
		DEFAULT_MODEL_EMBEDDING: "@cf/baai/bge-large-en-v1.5";
		PARENT_DRIVE_FOLDER_ID: "1jCokY9_gi3w3_qjdCX8MbnbtZrF9p52j";
		HEALTH_CHECK_DRIVE_FOLDER_ID: "1Sc-uzcth6LfaaDvWsTI7tCcbzL1eTwym";
		AI_GATEWAY_ID: "job-hunt";
		AI_GATEWAY_NAME: "default-gateway";
		CAREER_NOTEBOOKLM_ID: "ae2a743f-231b-4b05-ab98-683d01dd5c65";
		MODEL_CHAT: "@cf/openai/gpt-oss-120b";
		MODEL_EXTRACT: "@cf/openai/gpt-oss-120b";
		MODEL_DRAFT: "@cf/openai/gpt-oss-120b";
		MODEL_ANALYZE: "@cf/moonshotai/kimi-k2.5";
		MODEL_TRIAGE: "@cf/openai/gpt-oss-120b";
		MODEL_EMBED_JOBS: "gemini-embedding-001";
		MODEL_TRANSCRIBE: "@cf/openai/whisper-large-v3-turbo";
		BUCKET_NAME_AUDIO: "core-resumes-audio";
		BUCKET_NAME_FILES: "core-resumes-files";
		ROLE_PODCAST_POLL_INTERVAL: "5 minutes";
		ROLE_PODCAST_MAX_POLLS: "36";
		ROLE_PODCAST_SOURCE_WAIT_SECS: "300";
		GREENHOUSE_API_BASE: "https://boards-api.greenhouse.io/v1/boards";
		VECTORIZE_INDEX_NAME: "greenhouse-jobs";
		VECTORIZE_DIMENSIONS: "768";
		DEFAULT_BOARD_TOKENS: "cloudflare,vercel,anthropic,headway";
		ALLOWED_EMAILS: ["justin@126colby.com","jmbish04@gmail.com"];
		WORKER_EMAIL_INBOX: "job-pipeline@hacolby.app";
		GOOGLE_USER_TO_IMPERSONATE: string;
		R2_ACCESS_KEY_ID: string;
		R2_SECRET_ACCESS_KEY: string;
		OPENROUTE_API_KEY: string;
		ORCHESTRATOR_AGENT: DurableObjectNamespace<import("./dist/_worker.js/index").OrchestratorAgent>;
		NOTEBOOKLM_AGENT: DurableObjectNamespace<import("./dist/_worker.js/index").NotebookLMAgent>;
		NOTEBOOKLM_MCP_AGENT: DurableObjectNamespace<import("./dist/_worker.js/index").NotebookLMMcpAgent>;
		TRANSCRIPTION_AGENT: DurableObjectNamespace<import("./dist/_worker.js/index").TranscriptionAgent>;
		SANDBOX: DurableObjectNamespace<import("./dist/_worker.js/index").Sandbox>;
		JOB_SCANNER_AGENT: DurableObjectNamespace<import("./dist/_worker.js/index").JobScannerAgent>;
		JOB_ANALYSIS_AGENT: DurableObjectNamespace<import("./dist/_worker.js/index").JobAnalysisAgent>;
		SYNC_BROADCAST_AGENT: DurableObjectNamespace<import("./dist/_worker.js/index").SyncBroadcastAgent>;
		ROLE_CHAT_AGENT: DurableObjectNamespace<import("./dist/_worker.js/index").RoleChatAgent>;
		ROLE_ASSETS_WORKFLOW: Workflow<Parameters<import("./dist/_worker.js/index").RoleAssetsWorkflow['run']>[0]['payload']>;
		ROLE_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./dist/_worker.js/index").RoleAnalysisWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEFAULT_MODEL_EMBEDDING" | "PARENT_DRIVE_FOLDER_ID" | "HEALTH_CHECK_DRIVE_FOLDER_ID" | "AI_GATEWAY_ID" | "AI_GATEWAY_NAME" | "CAREER_NOTEBOOKLM_ID" | "MODEL_CHAT" | "MODEL_EXTRACT" | "MODEL_DRAFT" | "MODEL_ANALYZE" | "MODEL_TRIAGE" | "MODEL_EMBED_JOBS" | "MODEL_TRANSCRIBE" | "BUCKET_NAME_AUDIO" | "BUCKET_NAME_FILES" | "ROLE_PODCAST_POLL_INTERVAL" | "ROLE_PODCAST_MAX_POLLS" | "ROLE_PODCAST_SOURCE_WAIT_SECS" | "GREENHOUSE_API_BASE" | "VECTORIZE_INDEX_NAME" | "VECTORIZE_DIMENSIONS" | "DEFAULT_BOARD_TOKENS" | "ALLOWED_EMAILS" | "WORKER_EMAIL_INBOX" | "GOOGLE_USER_TO_IMPERSONATE" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY" | "OPENROUTE_API_KEY">> {}
}
