/**
 * @fileoverview NotebookLM Blobs management — list, clawback sources,
 * and soft-delete artifacts that are tracked in the notebooklm_blobs D1 table.
 */

import { ExternalLink, Loader2, Package, Trash2, Upload } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { apiDelete, apiGet } from "@/lib/api-client";

type BlobRow = {
  id: string;
  roleId: string;
  notebooklmId: string;
  notebooklmSourceUuid: string | null;
  notebooklmRemoteId: string | null;
  filename: string;
  md5: string | null;
  pipelineDocType: string;
  notebooklmType: "source" | "artifact";
  artifactStatus: string | null;
  r2Key: string | null;
  driveFileId: string | null;
  isActive: boolean;
  createdAt: string | null;
  updatedAt: string | null;
};

const DOC_TYPE_LABELS: Record<string, string> = {
  job_description: "Job Description",
  resume: "Resume",
  cover_letter: "Cover Letter",
  podcast: "Podcast",
  mind_map: "Mind Map",
  slide_deck: "Slide Deck",
  report: "Report",
  quiz: "Quiz",
  flashcards: "Flashcards",
  infographic: "Infographic",
  data_table: "Data Table",
  deep_research: "Deep Research",
  other: "Other",
};

export function NotebookLMBlobs({ roleId }: { roleId: string }) {
  const [blobs, setBlobs] = useState<BlobRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [deleteTarget, setDeleteTarget] = useState<BlobRow | null>(null);
  const [deleting, setDeleting] = useState(false);

  const load = useCallback(async () => {
    try {
      const data = await apiGet<BlobRow[]>(
        `/api/roles/${encodeURIComponent(roleId)}/notebooklm/blobs`,
      );
      setBlobs(data);
    } catch {
      // Silently fail
    } finally {
      setLoading(false);
    }
  }, [roleId]);

  useEffect(() => {
    void load();
  }, [load]);

  const sources = blobs.filter((b) => b.notebooklmType === "source" && b.isActive);
  const artifacts = blobs.filter((b) => b.notebooklmType === "artifact" && b.isActive);
  const inactive = blobs.filter((b) => !b.isActive);

  const handleDelete = async () => {
    if (!deleteTarget) return;
    setDeleting(true);

    try {
      const isSource = deleteTarget.notebooklmType === "source";
      const endpoint = isSource
        ? `/api/roles/${encodeURIComponent(roleId)}/notebooklm/blobs/${deleteTarget.id}/clawback`
        : `/api/roles/${encodeURIComponent(roleId)}/notebooklm/blobs/${deleteTarget.id}`;

      await apiDelete(endpoint);
      setDeleteTarget(null);
      void load();
    } catch {
      // handle error
    } finally {
      setDeleting(false);
    }
  };

  if (loading) {
    return (
      <div className="flex h-40 items-center justify-center">
        <Loader2 className="size-5 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="grid gap-4">
      {/* Sources */}
      <Card className="rounded-lg">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Upload className="size-4" />
                Sources ({sources.length})
              </CardTitle>
              <CardDescription>Files uploaded to NotebookLM as reference material</CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {sources.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No sources have been uploaded to NotebookLM for this role yet.
            </p>
          ) : (
            <div className="grid gap-2">
              {sources.map((blob) => (
                <BlobItem key={blob.id} blob={blob} onDelete={() => setDeleteTarget(blob)} />
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Artifacts */}
      <Card className="rounded-lg">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Package className="size-4" />
            Artifacts ({artifacts.length})
          </CardTitle>
          <CardDescription>
            Content generated by NotebookLM (podcasts, reports, mind maps, etc.)
          </CardDescription>
        </CardHeader>
        <CardContent>
          {artifacts.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No artifacts have been generated by NotebookLM for this role yet. Use the NotebookLM
              command menu to create one.
            </p>
          ) : (
            <div className="grid gap-2">
              {artifacts.map((blob) => (
                <BlobItem key={blob.id} blob={blob} onDelete={() => setDeleteTarget(blob)} />
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Inactive / deleted */}
      {inactive.length > 0 && (
        <Card className="rounded-lg opacity-60">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-muted-foreground">
              <Trash2 className="size-4" />
              Removed ({inactive.length})
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2">
              {inactive.map((blob) => (
                <BlobItem key={blob.id} blob={blob} />
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Delete confirmation dialog */}
      <AlertDialog open={!!deleteTarget} onOpenChange={(open) => !open && setDeleteTarget(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              {deleteTarget?.notebooklmType === "source" ? "Clawback Source" : "Remove Artifact"}
            </AlertDialogTitle>
            <AlertDialogDescription>
              {deleteTarget?.notebooklmType === "source"
                ? "This will permanently delete the source from the NotebookLM notebook. The source will no longer be available for AI analysis."
                : "This will hide the artifact from the dashboard. NotebookLM does not support deleting artifacts remotely."}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={deleting}>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={handleDelete} disabled={deleting}>
              {deleting ? "Removing..." : "Confirm"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

function BlobItem({ blob, onDelete }: { blob: BlobRow; onDelete?: () => void }) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-md border border-border/60 p-3">
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <span className="text-sm font-medium truncate">{blob.filename}</span>
          <Badge variant="secondary" className="text-[10px] shrink-0">
            {DOC_TYPE_LABELS[blob.pipelineDocType] ?? blob.pipelineDocType}
          </Badge>
          {blob.artifactStatus && (
            <Badge
              variant={
                blob.artifactStatus === "completed"
                  ? "default"
                  : blob.artifactStatus === "failed"
                    ? "destructive"
                    : "secondary"
              }
              className="text-[10px] shrink-0"
            >
              {blob.artifactStatus}
            </Badge>
          )}
        </div>
        <div className="mt-1 flex items-center gap-3 text-xs text-muted-foreground">
          <span>{blob.notebooklmType === "source" ? "Source" : "Artifact"}</span>
          {blob.createdAt && <span>{new Date(blob.createdAt).toLocaleDateString()}</span>}
          {blob.md5 && (
            <span className="font-mono truncate max-w-[120px]">{blob.md5.slice(0, 12)}…</span>
          )}
        </div>
      </div>
      <div className="flex items-center gap-1 shrink-0">
        {blob.driveFileId && (
          <a
            href={`https://drive.google.com/file/d/${blob.driveFileId}/view`}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center justify-center rounded-md border border-input bg-background p-1.5 text-sm hover:bg-accent"
          >
            <ExternalLink className="size-3.5" />
          </a>
        )}
        {blob.isActive && onDelete && (
          <Button
            variant="ghost"
            size="icon"
            className="size-7 text-destructive hover:text-destructive"
            onClick={onDelete}
          >
            <Trash2 className="size-3.5" />
          </Button>
        )}
      </div>
    </div>
  );
}
