import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

import { roles } from "./roles";

// ---------------------------------------------------------------------------
// Table & column documentation (consumed by /api/docs/schema)
// ---------------------------------------------------------------------------

/** Human-readable description of the `notebooklm_blobs` table for the documentation UI. */
export const NOTEBOOKLM_BLOBS_TABLE_DESCRIPTION =
  "Log table tracking every file uploaded to NotebookLM as a source and every artifact generated by NotebookLM, enabling deduplication, provenance tracking, and lifecycle management.";

/** Per-column descriptions surfaced in the documentation schema viewer. */
export const NOTEBOOKLM_BLOBS_COLUMN_DESCRIPTIONS: Record<string, string> = {
  id: "UUID primary key auto-generated for each blob log entry.",
  role_id: "Foreign key to the role this source/artifact is associated with.",
  notebooklm_id:
    "The NotebookLM notebook ID used when adding/retrieving this blob. Maps to env.CAREER_NOTEBOOKLM_ID.",
  notebooklm_msg_id:
    "D1 identifier for the message/thread entry that initiated or triggered this blob operation.",
  notebooklm_source_uuid:
    "UUID generated by our system, used as the filename when uploading sources to NotebookLM. Also used to cross-reference with the notebook's source list.",
  notebooklm_remote_id:
    "The ID returned by the NotebookLM SDK after a source is uploaded or an artifact is created. Used for SDK CRUD operations.",
  filename:
    "The actual filename of the blob. For sources, this is the UUID-based filename we upload. For artifacts, this is the artifact name from NotebookLM.",
  md5: "MD5 hash of the blob content, used to prevent duplicate source uploads to NotebookLM.",
  pipeline_doc_type:
    "What type of document this blob represents in the job seeker pipeline (e.g., job_description, resume, podcast, mind_map, slide_deck, report, quiz, flashcards, infographic, data_table, deep_research).",
  notebooklm_type:
    "Whether this blob is a 'source' (uploaded to NotebookLM) or an 'artifact' (generated by NotebookLM).",
  artifact_status:
    "For artifacts: tracks the generation lifecycle (requested, polling, completed, failed). Null for sources.",
  r2_key: "R2 bucket key if the blob content has been downloaded and stored in R2.",
  drive_file_id: "Google Drive file ID if the blob has been uploaded to the role's Drive folder.",
  is_active:
    "Whether this blob is currently live in NotebookLM. Set to false on clawback (source) or soft-delete (artifact).",
  created_at: "Unix timestamp (seconds) of when this blob record was created.",
  updated_at: "Unix timestamp (seconds) of the last modification.",
};

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

export const notebooklmBlobs = sqliteTable(
  "notebooklm_blobs",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    roleId: text("role_id")
      .notNull()
      .references(() => roles.id, { onDelete: "cascade" }),
    notebooklmId: text("notebooklm_id").notNull(),
    notebooklmMsgId: text("notebooklm_msg_id"),
    notebooklmSourceUuid: text("notebooklm_source_uuid"),
    notebooklmRemoteId: text("notebooklm_remote_id"),
    filename: text("filename").notNull(),
    md5: text("md5"),
    pipelineDocType: text("pipeline_doc_type", {
      enum: [
        "job_description",
        "resume",
        "cover_letter",
        "podcast",
        "mind_map",
        "slide_deck",
        "report",
        "quiz",
        "flashcards",
        "infographic",
        "data_table",
        "deep_research",
        "other",
      ],
    }).notNull(),
    notebooklmType: text("notebooklm_type", {
      enum: ["source", "artifact"],
    }).notNull(),
    artifactStatus: text("artifact_status", {
      enum: ["requested", "polling", "completed", "failed"],
    }),
    r2Key: text("r2_key"),
    driveFileId: text("drive_file_id"),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    roleIdx: index("notebooklm_blobs_role_id_idx").on(table.roleId),
    typeIdx: index("notebooklm_blobs_type_idx").on(table.notebooklmType),
    sourceUuidIdx: index("notebooklm_blobs_source_uuid_idx").on(table.notebooklmSourceUuid),
    md5Idx: index("notebooklm_blobs_md5_idx").on(table.md5),
    activeIdx: index("notebooklm_blobs_active_idx").on(table.isActive),
    docTypeIdx: index("notebooklm_blobs_doc_type_idx").on(table.pipelineDocType),
  }),
);

export const insertNotebooklmBlobSchema = createInsertSchema(notebooklmBlobs);
export const selectNotebooklmBlobSchema = createSelectSchema(notebooklmBlobs);
export type NotebooklmBlob = typeof notebooklmBlobs.$inferSelect;
export type NewNotebooklmBlob = typeof notebooklmBlobs.$inferInsert;
